#include <stdio.h>

const char* obelixString =" __________________________________________________________________________________________ \n"
                          "| __-*                                                                                *-__ |\n"
                          "|/       IIIII L     SSSSS   SSSSS OOOOO NN   N TTTTTTT   FFFFFF OOOOO U   U SSSSS        \\|\n"
                          "|          I   L     S       S     O   O N N  N    T      F      O   O U   U S             |\n"
                          "|          I   L     SSSSS   SSSSS O   O N  N N    T      FFF    O   O U   U SSSSS         |\n"
                          "|          I   l         S       S O   O N   NN    T      F      O   O U   U     S         |\n"
                          "|        IIIII LLLLL SSSSS   SSSSS OOOOO N    N    T      F      OOOOO  UUU  SSSSS         |\n"
                          "|                                                                                          |\n"
                          "|            CCC EEEEE SSSSS   RRRR  OOOOO MM   MM     A     IIIII NN   N SSSSS            |\n"
                          "|           C    E     S       R   R O   O M M M M    A A      I   N N  N S                |\n"
                          "|           C    EEE   SSSSS   RRRR  O   O M  M  M   A   A     I   N  N N SSSSS         _-*|\n"
                          "|           C    E         S   R  R  O   O M     M  AAAAAZA    I   N   NN     S     _--*   |\n"
                          "|*---___     CCC EEEEE SSSSS   R   R OOOOO M     M A       A IIIII N    N SSSSS  __*       |\n"
                          "|       **---___                                                            __---*         |\n"
                          "|               **---______                                     _____-----**               |\n"
                          "|                          ***********------_____  _____-----***                           |\n"
                          "|                                                \\ \\                                       |\n"
                          "|                                                 \\ \\   ___________            _______     |\n"
                          "|                                                  \\ \\ |____   ____|  /\\      |  ___  |    |\n"
                          "|              ___________              _______     \\ \\     | |      /  \\     | |   | |    |\n"
                          "|             |____   ____|    /\\      |  ___  |    / /     | |     / /\\ \\    | |___| |    |\n"
                          "|                  | |        /  \\     | |   | |   / /      | |    / /__\\ \\   |  _____|    |\n"
                          "|                  | |       / /\\ \\    | |___| |  / /       | |   / ______ \\  | |          |\n"
                          "|                  | |      / /__\\ \\   |  _____| | |        |_|  /_/      \\_\\ |_|          |\n"
                          "|                  | |     / ______ \\  | |        \\ \\                                      |\n"
                          "|                  |_|    /_/      \\_\\ |_|         \\ \\                                     |\n"
                          "|                                                   \\ \\                                    |\n"
                          "|   ___________              _______                 \\|                                    |\n"
                          "|  |____   ____|    /\\      |  ___  |      __--__                                          |\n"
                          "|       | |        /  \\     | |   | |    /cCCCCCc\\                                         |\n"
                          "|       | |       / /\\ \\    | |___| |    |-_--___/-------___   __                          |\n"
                          "|       | |      / /__\\ \\   |  _____|    \\_ CCCC CCCCCCCCCCC\\_/*/\\                         |\n"
                          "|       | |     / ______ \\  | |           /C CCC CCCCCCCCc--__\\/ /                         |\n"
                          "|       |_|    /_/      \\_\\ |_|          /CCCCCCC_/            \\/                          |\n"
                          "|                                       /CCCCC_/M/              \\                          |\n"
                          "|                                      |CCC/MMMM|!_/\\_          \\                          |\n"
                          "|          ____---__                   |C/MMMMMM_/    \\_       _/|      ______             |\n"
                          "|    __---*         \\                  |/MMMMMM/       /\\_ /\\/   |__--**      *_           |\n"
                          "|__-*      _       _/          __---__ /MMMMMMM       /##  |##--*               \\          |\n"
                          "|     ________----*         _ /       \\|MMMMMMM        \\_/  \\/                    \\        |\n"
                          "|__--*_____\\__             /      __   |MMMMMM/    /_                              |       |\n"
                          "|__-**      ___\\          /      /  \\  |MMMMM/                                     |       |\n"
                          "|    __ __/    \\          \\     |  ###-/MMMM/       _---*/                        /        |\n"
                          "| __-__/        \\          \\_   \\__\\__/MMMM/    _--* MMMM|                       /         |\n"
                          "|*           -   \\      ___  \\      /MMMMM/  __/MMMMMMMMM\\_                    _/          |\n"
                          "|          _//* _/ mmmm/mmmm\\/mmmm/MMMMMM|\\_/MMMMMMMMMMMMMM\\_               __/            |\n"
                          "|           \\__/ /MMMM MMMM/MMMMM MMMMMM/ \\MMMMMMMMMMM----/  *\\__________--*               |\n"
                          "|             \\  \\mmm/\\mmm/\\MMMMM\\MMMMM/            \\          \\__/MMMMMM\\___              |\n"
                          "|              \\  ___*---     /                      \\_         \\ \\MMMMLMMM/               |\n"
                          "|*-_                                                   \\_      _/      |                   |\n"
                          "|   \\        _/   / __        \\                          *----*        |_                  |\n"
                          "|    \\     _/   _/    \\_       \\                                       | *-_               |\n"
                          "|              /      \\_**-_    \\                                     /     *--_           |\n"
                          "|           |           \\   *-_  \\                                   /          --_        |\n"
                          "|           |          \\ \\     *-_\\_                                 |             *_      |\n"
                          "|           /           \\ \\       \\_\\_                             _/   _--*         *_    |\n"
                          "|          /           \\ \\ \\          *--__                      _/___-*               *-_ |\n"
                          "|         /                                *-__                _/                         *|\n"
                          "|______________________________________________\\______________/____________________________|\n";

int main(int argc, char *argv[]) {

    printf("%s", obelixString);
    return 0;
}
