name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install libs
        run: |
          sudo apt-get install make
          sudo apt-get install gcc
          sudo apt-get install nasm
      - name: make
        run: make
